name: Conan Package
run-name: ${{ github.actor }} packaging project
on: [push]
jobs:
  Package:
    runs-on: ubuntu-latest
    steps:
      - name: Install Conan
        id: conan
        uses: turtlebrowser/get-conan@main
      - name: Conan version
        run: echo "${{ steps.conan.outputs.version }}"
      - name: Conan Create
        run: ls && conan create ..
